# Generated by Django 5.2.2 on 2025-07-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
