# Generated by Django 5.2.2 on 2025-08-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
